In [2]:
import numpy as np
A = np.matrix('3 1; 8 2')
A

matrix([[3, 1],
        [8, 2]])

In [3]:
B = np.matrix('6 1; 7 9')
B

matrix([[6, 1],
        [7, 9]])

In [4]:
A @ B

matrix([[25, 12],
        [62, 26]])

In [5]:
A*B

matrix([[25, 12],
        [62, 26]])

In [13]:
A = np.matrix('3 1; 8 2')
batch_size = 2
A. sum (axis = 1)

matrix([[ 4],
        [10]])

In [ ]:
        grad['b'] = np.sum(dv_output, 1, keepdims=True) / batch_size