In [13]:
import numpy as np
coordinates = np.random.randint(0, 100, size=(30,30, 30, 15))

In [8]:
m2 = np.random.randint(0, 100, size=(15))

In [9]:
coordinates @ m2

array([37362, 34565, 48634, 33786, 49561, 59924, 50605, 52136, 53558,
       37551, 50420, 48293, 43780, 47493, 46357, 51694, 44672, 60497,
       52336, 53300, 48402, 60671, 43422, 38337, 46311, 46240, 45710,
       33957, 50701, 57942])

In [14]:
coordinates.sum(axis = (0,1))

array([[43771, 45715, 44252, 45647, 43558, 43686, 44177, 44463, 44231,
        44740, 44855, 44047, 45093, 44354, 44759],
       [44117, 45105, 45926, 43412, 44188, 44695, 44299, 44540, 45228,
        46136, 45983, 43900, 43934, 42758, 44677],
       [44457, 44914, 44353, 45737, 44838, 45241, 45539, 44606, 43358,
        43721, 46432, 43904, 45096, 45277, 45252],
       [45714, 45932, 43732, 44534, 44625, 43701, 44123, 46430, 43329,
        44849, 44498, 44821, 44587, 44514, 45853],
       [43249, 43543, 45461, 45972, 45692, 44657, 44772, 46010, 43948,
        44399, 45024, 45518, 45206, 46232, 45234],
       [44665, 44475, 45476, 44040, 44391, 46259, 44711, 44188, 44566,
        43701, 43665, 46192, 43796, 46706, 45187],
       [43941, 43314, 43897, 44497, 43818, 44684, 44180, 44481, 43561,
        44773, 44916, 45033, 45668, 41827, 45593],
       [44908, 42977, 45550, 45194, 43466, 43586, 45651, 44452, 44963,
        44561, 45280, 43521, 43557, 43497, 45866],
       [45659, 43859, 44

In [4]:
A = np.array([[1,2,3],[4,5,6]])
np.rot90(A, 2)

array([[6, 5, 4],
       [3, 2, 1]])

In [5]:
np.flip(A)

array([[6, 5, 4],
       [3, 2, 1]])

In [17]:
np.sum(coordinates, (0, 1,3))[:, np.newaxis]

array([[667348],
       [668898],
       [672725],
       [671242],
       [674917],
       [672018],
       [664183],
       [667029],
       [671092],
       [671371],
       [662118],
       [659300],
       [660916],
       [667021],
       [674719],
       [669396],
       [671247],
       [671390],
       [672116],
       [664684],
       [667303],
       [662944],
       [665348],
       [666457],
       [671120],
       [667081],
       [667545],
       [666669],
       [671088],
       [673286]])

In [18]:
np.sum(coordinates, (0, 1,3)).reshape(-1,1)

array([[667348],
       [668898],
       [672725],
       [671242],
       [674917],
       [672018],
       [664183],
       [667029],
       [671092],
       [671371],
       [662118],
       [659300],
       [660916],
       [667021],
       [674719],
       [669396],
       [671247],
       [671390],
       [672116],
       [664684],
       [667303],
       [662944],
       [665348],
       [666457],
       [671120],
       [667081],
       [667545],
       [666669],
       [671088],
       [673286]])

In [4]:
import numpy as np
m2 = np.random.randint(0, 100, size=(3,5))   
ind1 = np.arange(m2.shape[1])

In [5]:
m2

array([[66, 18, 80, 41, 94],
       [81, 46, 27, 53, 59],
       [63, 16, 43, 14, 91]])

In [6]:
ind1

array([0, 1, 2, 3, 4])

In [10]:
m1 = np.random.randint(0, 100, size=(3)) 
ind0 = np.squeeze(m1)
m1,ind0

(array([57, 18, 12]), array([57, 18, 12]))

In [ ]:
m1 = np.random.randint(0, 100, size=(3))